/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Health check endpoint for Kubernetes probes.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marble/v1/media-assets/{media_asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media Asset
         * @description Get a media asset by ID.
         *
         *     Retrieves metadata for a previously created media asset.
         *
         *     Args:
         *         media_asset_id: The media asset identifier.
         *
         *     Returns:
         *         MediaAsset object with media_asset_id, file_name, extension, kind,
         *         metadata, created_at, and updated_at.
         *
         *     Raises:
         *         HTTPException: 404 if not found
         */
        get: operations["get_media_asset_marble_v1_media_assets__media_asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marble/v1/media-assets:prepare_upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare a media asset upload
         * @description Prepare a media asset upload for use in world generation.
         *
         *     This API endpoint creates a media asset record and returns a signed upload URL.
         *     Use this workflow to upload images or videos that you want to reference in world
         *     generation requests.
         *
         *     ## Workflow
         *
         *     1. **Prepare Upload** (this endpoint): Get a `media_asset_id` and `upload_url`
         *     2. **Upload File**: Use the signed URL to upload your file
         *     3. **Generate World**: Reference the `media_asset_id` in `/worlds:generate` with
         *        source type "media_asset"
         *
         *     ## Request Parameters
         *
         *     - `file_name`: Your file's name (e.g., "landscape.jpg")
         *     - `extension`: File extension without dot (e.g., "jpg", "png", "mp4")
         *     - `kind`: Either "image" or "video"
         *     - `metadata`: Optional custom metadata object
         *
         *     ## Response
         *
         *     Returns a `MediaAssetPrepareUploadResponse` containing:
         *
         *     - `media_asset`: Object with `media_asset_id` (use this in world generation)
         *     - `upload_info`: Object with `upload_url`, `required_headers`, and `curl_example`
         *
         *     ## Uploading Your File
         *
         *     Use the returned `upload_url` and `required_headers` to upload your file:
         *
         *     ```bash
         *     curl --request PUT \
         *       --url <upload_url> \
         *       --header "Content-Type: <content-type>" \
         *       --header "<header-name>: <header-value>" \
         *       --upload-file /path/to/your/file
         *     ```
         *
         *     Replace:
         *     - `<upload_url>`: The `upload_url` from the response
         *     - `<content-type>`: MIME type (e.g., `image/png`, `image/jpeg`, `video/mp4`)
         *     - `<header-name>: <header-value>`: Each header from `required_headers`
         *     - `/path/to/your/file`: Path to your local file
         *
         *     ## Example Usage in World Generation
         *
         *     After uploading, use the `media_asset_id` in a world generation request:
         *
         *     ```json
         *     {
         *       "world_prompt": {
         *         "type": "image",
         *         "image_prompt": {
         *           "source": "media_asset",
         *           "media_asset_id": "<your-media-asset-id>"
         *         }
         *       }
         *     }
         *     ```
         */
        post: operations["prepare_media_asset_upload_marble_v1_media_assets_prepare_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marble/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operation
         * @description Get an operation by ID.
         *
         *     Poll this endpoint to check the status of a long-running operation.
         *     When done=true, the response field contains the generated world.
         *
         *     Args:
         *         operation_id: The operation identifier from /worlds:generate.
         *
         *     Returns:
         *         GetOperationResponse[World] with:
         *             - operation_id: Operation identifier
         *             - created_at: Creation timestamp
         *             - updated_at: Last update timestamp
         *             - expires_at: Expiration timestamp
         *             - done: true when complete, false while in progress
         *             - error: Error details if failed, null otherwise
         *             - metadata: Progress information and world_id
         *             - response: Generated World if done=true, null otherwise
         *
         *     Raises:
         *         HTTPException: 401 if unauthorized
         *         HTTPException: 404 if operation not found
         *         HTTPException: 500 if request fails
         */
        get: operations["get_operation_marble_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marble/v1/pano:depth_to_rgb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pano Depth To Rgb
         * @description Generate an RGB panorama from a depth panorama.
         *
         *     Provide a depth panorama and a text prompt
         *     describing the desired appearance. The depth map
         *     supplies the scene geometry; the model synthesizes
         *     textures that match that geometry and returns a
         *     panoramic RGB image.
         *
         *     Accepted depth inputs:
         *
         *     * **EXR**: float depth values. Omit
         *       ``z_min`` and ``z_max``.
         *     * **PNG**: depth values normalized to [0, 1].
         *       Provide both ``z_min`` and ``z_max`` so the
         *       service can decode the PNG correctly.
         *
         *     For a complete PNG-based workflow, see the
         *     [web-chisel-depth-png example](https://github.com/worldlabsai/worldlabs-api-examples/tree/main/web-chisel-depth-png).
         *
         *     Returns a long-running ``Operation``. Poll
         *     ``GET /operations/{operation_id}`` until
         *     ``done`` is ``true``, then read the generated
         *     panorama URL from ``response.pano_url``.
         *
         *     Raises:
         *         HTTPException: 400 if invalid request
         *         HTTPException: 402 if insufficient credits
         *         HTTPException: 500 if generation could not start
         */
        post: operations["pano_depth_to_rgb_marble_v1_pano_depth_to_rgb_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marble/v1/worlds/{world_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get World
         * @description Get a world by ID.
         *
         *     Retrieves a world's details including generated assets if available.
         *     Only the world owner or users with access to public worlds can retrieve them.
         *
         *     Args:
         *         world_id: The unique identifier of the world.
         *
         *     Returns:
         *         World object with world_id, display_name, tags, assets, created_at,
         *         updated_at, permission, model, world_prompt, and world_marble_url.
         *
         *     Raises:
         *         HTTPException: 404 if world not found or access denied
         */
        get: operations["get_world_marble_v1_worlds__world_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete World
         * @description Delete a world by ID.
         *
         *     Permanently deletes a world and its associated assets.
         *     Only the world owner can delete a world.
         *
         *     Args:
         *         world_id: The unique identifier of the world to delete.
         *
         *     Returns:
         *         DeleteWorldResponse confirming the deletion.
         *
         *     Raises:
         *         HTTPException: 403 if user is not the world owner
         *         HTTPException: 404 if world not found
         *         HTTPException: 500 if deletion fails
         */
        delete: operations["delete_world_marble_v1_worlds__world_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marble/v1/worlds:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate World
         * @description Start world generation.
         *
         *     Creates a new world generation job and returns a long-running operation.
         *     Poll the /operations/{operation_id} endpoint to check generation status
         *     and retrieve the generated world when complete.
         *
         *     Args:
         *         request: The world generation request containing world_prompt, display_name,
         *             tags, model, seed, and permission settings.
         *
         *     Returns:
         *         GenerateWorldResponse with operation_id and timestamps. Use the operation_id
         *         to poll for completion.
         *
         *     Raises:
         *         HTTPException: 400 if invalid request or content violates policies
         *         HTTPException: 402 if insufficient credits
         *         HTTPException: 500 if generation could not be started
         */
        post: operations["generate_world_marble_v1_worlds_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marble/v1/worlds:list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List Worlds
         * @description List worlds with optional filters.
         *
         *     Returns worlds created through the API with optional filtering and pagination.
         *
         *     Args:
         *         request: List request with optional filters:
         *             - page_size: Number of results per page (default: 10)
         *             - page_token: Pagination token from previous response
         *             - status: Filter by status (e.g., "COMPLETED")
         *             - model: Filter by model name (e.g., "marble-1.0-plus")
         *             - tags: Filter by tags (matches worlds with any tag)
         *             - is_public: Filter by visibility (true=public, false=private, null=all)
         *             - created_after: Filter by creation time (after timestamp)
         *             - created_before: Filter by creation time (before timestamp)
         *             - sort_by: Sort order ("created_at" or "updated_at")
         *
         *     Returns:
         *         ListWorldsResponse with worlds list and next_page_token for pagination.
         *
         *     Raises:
         *         HTTPException: 400 if invalid parameters
         *         HTTPException: 500 if request fails
         */
        post: operations["list_worlds_marble_v1_worlds_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Content
         * @description Represents content (media, text, images) that can be stored inline or via URL.
         *
         *     Supports both direct data storage (up to 10MB) and URL references (up to 20MB).
         */
        Content: {
            /** Data Base64 */
            data_base64?: string | null;
            /**
             * Extension
             * @description File extension without dot
             * @example jpg
             * @example png
             * @example pdf
             * @example txt
             */
            extension?: string | null;
            /** Uri */
            uri?: string | null;
        };
        /**
         * DataBase64Reference
         * @description Reference to content via base64-encoded data.
         */
        DataBase64Reference: {
            /**
             * Data Base64
             * @description Base64-encoded content data
             */
            data_base64: string;
            /**
             * Extension
             * @description File extension without dot (e.g., 'jpg', 'png')
             */
            extension?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "data_base64";
        };
        /**
         * DeleteWorldResponse
         * @description Response from world deletion endpoint.
         */
        DeleteWorldResponse: {
            /**
             * Deleted
             * @description Whether the world was successfully deleted
             */
            deleted: boolean;
            /**
             * World Id
             * @description ID of the deleted world
             */
            world_id: string;
        };
        /**
         * DepthPanoPrompt
         * @description For models conditioned on a depth pano and text.
         *     When depth_pano_image is a log-encoded PNG, z_min and z_max are required
         *     to decode it correctly. When it is an EXR file containing raw float depth
         *     values, z_min and z_max will both be ignored.
         *     Please set z_min and z_max both to None when using an EXR file.
         */
        DepthPanoPrompt: {
            depth_pano_image: components["schemas"]["Content"];
            /** Text Prompt */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "depth-pano";
            /** Z Max */
            z_max?: number | null;
            /** Z Min */
            z_min?: number | null;
        };
        /**
         * GenerateWorldResponse
         * @description Response from world generation endpoint.
         */
        GenerateWorldResponse: {
            /**
             * Created At
             * @description Creation timestamp
             */
            created_at?: string | null;
            /**
             * Done
             * @description True if the operation is completed
             */
            done: boolean;
            /** @description Error information if the operation failed */
            error?: components["schemas"]["OperationError"] | null;
            /**
             * Expires At
             * @description Expiration timestamp
             */
            expires_at?: string | null;
            /**
             * Metadata
             * @description Service-specific metadata, such as progress percentage
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Operation Id
             * @description Operation identifier
             */
            operation_id: string;
            /**
             * Response
             * @description Result payload when done=true and no error. Structure depends on operation type.
             */
            response?: unknown | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /** GetOperationResponse[Union[World, PanoDepthToRgbResult]] */
        GetOperationResponse_Union_World__PanoDepthToRgbResult__: {
            /**
             * Created At
             * @description Creation timestamp
             */
            created_at?: string | null;
            /**
             * Done
             * @description True if the operation is completed
             */
            done: boolean;
            /** @description Error information if the operation failed */
            error?: components["schemas"]["OperationError"] | null;
            /**
             * Expires At
             * @description Expiration timestamp
             */
            expires_at?: string | null;
            /**
             * Metadata
             * @description Service-specific metadata, such as progress percentage
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Operation Id
             * @description Operation identifier
             */
            operation_id: string;
            /**
             * Response
             * @description Result payload when done=true and no error. Structure depends on operation type.
             */
            response?: components["schemas"]["World"] | components["schemas"]["PanoDepthToRgbResult"] | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImagePrompt
         * @description Image-to-world generation.
         *
         *     Generates a world from an image. text_prompt is optional - if not provided,
         *     it will be generated via recaptioning.
         *
         *     Recommended image formats: jpg, jpeg, png, webp.
         */
        ImagePrompt: {
            /**
             * Disable Recaption
             * @description If True, use text_prompt as-is without recaptioning
             */
            disable_recaption?: boolean | null;
            /**
             * Image Prompt
             * @description Image content for world generation
             */
            image_prompt: components["schemas"]["MediaAssetReference"] | components["schemas"]["UriReference"] | components["schemas"]["DataBase64Reference"];
            /**
             * Is Pano
             * @description Whether the provided image is already a panorama
             */
            is_pano?: boolean | null;
            /**
             * Text Prompt
             * @description Optional text guidance (auto-generated if not provided)
             */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
        };
        /**
         * ImageryAssets
         * @description Imagery asset URLs.
         */
        ImageryAssets: {
            /**
             * Pano Url
             * @description Panorama image URL
             */
            pano_url?: string | null;
        };
        /**
         * InpaintPanoPrompt
         * @description For models that inpaint the masked portion of a pano image.
         */
        InpaintPanoPrompt: {
            pano_image: components["schemas"]["Content"];
            pano_mask: components["schemas"]["Content"];
            /** Text Prompt */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "inpaint-pano";
        };
        /**
         * ListWorldsRequest
         * @description Request to list API-generated worlds with optional filters.
         * @example {
         *       "model": "marble-1.0",
         *       "page_size": 20,
         *       "sort_by": "created_at",
         *       "status": "SUCCEEDED"
         *     }
         * @example {
         *       "page_size": 50,
         *       "sort_by": "created_at",
         *       "status": "SUCCEEDED",
         *       "tags": [
         *         "fantasy",
         *         "nature"
         *       ]
         *     }
         * @example {
         *       "created_after": "2024-01-01T00:00:00Z",
         *       "created_before": "2024-12-31T23:59:59Z",
         *       "page_size": 100,
         *       "sort_by": "created_at"
         *     }
         * @example {
         *       "model": "marble-1.0-draft",
         *       "page_size": 30,
         *       "tags": [
         *         "landscape"
         *       ]
         *     }
         * @example {
         *       "page_size": 20,
         *       "page_token": "eyJzbmFwc2hvdF90aW1lIjoiMjAyNC0wMS0wMVQwMDowMDowMFoiLCJsYXN0X2NyZWF0ZWRfYXQiOiIyMDI0LTAxLTAxVDAwOjAwOjAwWiIsImxhc3RfaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAifQ==",
         *       "sort_by": "created_at"
         *     }
         */
        ListWorldsRequest: {
            /**
             * Created After
             * @description Filter worlds created after this timestamp (inclusive)
             */
            created_after?: string | null;
            /**
             * Created Before
             * @description Filter worlds created before this timestamp (exclusive)
             */
            created_before?: string | null;
            /**
             * Is Public
             * @description Filter by visibility. true=public only, false=private only, null=all
             */
            is_public?: boolean | null;
            /**
             * Model
             * @description Filter by model used for generation. Legacy names are deprecated; use the new lowercase names.
             */
            model?: ("marble-1.0-draft" | "marble-1.0" | "marble-1.1" | "marble-1.1-plus") | ("Marble 0.1-mini" | "Marble 0.1-plus" | "Marble 1.1-plus") | null;
            /**
             * Page Size
             * @description Number of results per page (1-100)
             * @default 20
             */
            page_size: number;
            /**
             * Page Token
             * @description Cursor token for pagination (opaque base64 string from previous response). Use cursor from next_page_token in previous response for consistent pagination.
             */
            page_token?: string | null;
            /**
             * Sort By
             * @description Sort results by created_at or updated_at
             * @default created_at
             * @enum {string}
             */
            sort_by: "created_at" | "updated_at";
            /**
             * Status
             * @description Filter by world status
             */
            status?: ("SUCCEEDED" | "PENDING" | "FAILED" | "RUNNING") | null;
            /**
             * Tags
             * @description Filter by tags (returns worlds with ANY of these tags)
             */
            tags?: string[] | null;
        };
        /**
         * ListWorldsResponse
         * @description Response containing a list of API-generated worlds.
         */
        ListWorldsResponse: {
            /**
             * Next Page Token
             * @description Token for fetching the next page of results
             */
            next_page_token?: string | null;
            /**
             * Worlds
             * @description List of worlds
             */
            worlds: components["schemas"]["World"][];
        };
        /**
         * MediaAsset
         * @description A user-uploaded media asset stored in managed storage.
         *
         *     MediaAssets can be images, videos, or binary blobs that are used
         *     as input to world generation.
         */
        MediaAsset: {
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Extension
             * @description File extension without dot
             * @example mp4
             * @example png
             * @example jpg
             */
            extension?: string | null;
            /**
             * File Name
             * @description File name
             */
            file_name: string;
            /**
             * @description High-level media type
             * @example image
             * @example video
             */
            kind: components["schemas"]["MediaAssetKind"];
            /**
             * Media Asset Id
             * @description Server-generated media asset identifier
             */
            media_asset_id: string;
            /**
             * Metadata
             * @description Optional application-specific metadata
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /**
         * MediaAssetKind
         * @description High-level media asset type.
         * @enum {string}
         */
        MediaAssetKind: "image" | "video";
        /**
         * MediaAssetPrepareUploadRequest
         * @description Request to prepare a media asset upload.
         */
        MediaAssetPrepareUploadRequest: {
            /**
             * Extension
             * @description File extension without dot
             * @example mp4
             * @example png
             * @example jpg
             */
            extension?: string | null;
            /**
             * File Name
             * @description File name
             */
            file_name: string;
            /**
             * @description High-level media type
             * @example image
             * @example video
             */
            kind: components["schemas"]["MediaAssetKind"];
            /**
             * Metadata
             * @description Optional application-specific metadata
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * MediaAssetPrepareUploadResponse
         * @description Response from preparing a media asset upload.
         */
        MediaAssetPrepareUploadResponse: {
            /** @description The created media asset */
            media_asset: components["schemas"]["MediaAsset"];
            /** @description Upload URL information */
            upload_info: components["schemas"]["UploadUrlInfo"];
        };
        /**
         * MediaAssetReference
         * @description Reference to a previously uploaded MediaAsset.
         */
        MediaAssetReference: {
            /**
             * Media Asset Id
             * @description ID of a MediaAsset resource previously created and marked READY
             */
            media_asset_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "media_asset";
        };
        /**
         * MeshAssets
         * @description Mesh asset URLs.
         */
        MeshAssets: {
            /**
             * Collider Mesh Url
             * @description Collider mesh URL
             */
            collider_mesh_url?: string | null;
        };
        /**
         * MultiImagePrompt
         * @description Multi-image-to-world generation.
         *
         *     Generates a world from multiple images. text_prompt is optional.
         *
         *     Recommended image formats: jpg, jpeg, png, webp.
         */
        "MultiImagePrompt-Input": {
            /**
             * Disable Recaption
             * @description If True, use text_prompt as-is without recaptioning
             */
            disable_recaption?: boolean | null;
            /**
             * Multi Image Prompt
             * @description List of images with optional spherical locations
             */
            multi_image_prompt: components["schemas"]["SphericallyLocatedContent-Input"][];
            /**
             * Reconstruct Images
             * @description Whether to use reconstruction mode (allows up to 8 images, otherwise 4)
             * @default false
             */
            reconstruct_images: boolean;
            /**
             * Text Prompt
             * @description Optional text guidance (auto-generated if not provided)
             */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multi-image";
        };
        /**
         * MultiImagePrompt
         * @description For world models supporting multi-image (+ text) input.
         */
        "MultiImagePrompt-Output": {
            /** Multi Image Prompt */
            multi_image_prompt: components["schemas"]["SphericallyLocatedContent-Output"][];
            /**
             * Reconstruct Images
             * @default false
             */
            reconstruct_images: boolean;
            /** Text Prompt */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multi-image";
        };
        /**
         * OperationError
         * @description Error information for a failed operation.
         */
        OperationError: {
            /**
             * Code
             * @description Error code
             */
            code?: number | null;
            /**
             * Message
             * @description Error message
             */
            message?: string | null;
        };
        /** Operation[PanoDepthToRgbResult] */
        Operation_PanoDepthToRgbResult_: {
            /**
             * Created At
             * @description Creation timestamp
             */
            created_at?: string | null;
            /**
             * Done
             * @description True if the operation is completed
             */
            done: boolean;
            /** @description Error information if the operation failed */
            error?: components["schemas"]["OperationError"] | null;
            /**
             * Expires At
             * @description Expiration timestamp
             */
            expires_at?: string | null;
            /**
             * Metadata
             * @description Service-specific metadata, such as progress percentage
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Operation Id
             * @description Operation identifier
             */
            operation_id: string;
            /** @description Result payload when done=true and no error. Structure depends on operation type. */
            response?: components["schemas"]["PanoDepthToRgbResult"] | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /**
         * PanoDepthToRgbRequest
         * @description Request to generate an RGB panorama from a depth panorama.
         *
         *     Provide a depth panorama and a text prompt describing
         *     the desired appearance. The depth map supplies the
         *     scene geometry; the model synthesizes textures that
         *     loosely adhere to that geometry and returns a panoramic RGB image.
         *
         *     Accepted depth inputs:
         *
         *     * **EXR**: float depth values. Omit ``z_min``
         *       and ``z_max``.
         *     * **PNG**: depth values normalized to [0, 1].
         *       Provide both ``z_min`` and ``z_max`` so the service
         *       can decode the PNG back into metric depth.
         *
         *     For a complete PNG-based workflow, see the
         *     `web-chisel-depth-png example <https://github.com/worldlabsai/worldlabs-api-examples/tree/main/web-chisel-depth-png>`.
         *
         *     This endpoint returns a long-running ``Operation``.
         *     Poll ``GET /operations/{operation_id}`` until
         *     ``done`` is ``true``, then read the generated
         *     panorama URL from ``response.pano_url``.
         * @example {
         *       "depth_pano_image": {
         *         "source": "uri",
         *         "uri": "https://example.com/depth.exr"
         *       },
         *       "text_prompt": "A cozy cabin interior with warm wooden walls"
         *     }
         * @example {
         *       "depth_pano_image": {
         *         "source": "uri",
         *         "uri": "https://example.com/depth.png"
         *       },
         *       "text_prompt": "A futuristic space station",
         *       "z_max": 100,
         *       "z_min": 0.1
         *     }
         */
        PanoDepthToRgbRequest: {
            /**
             * Depth Pano Image
             * @description Depth panorama image (EXR or PNG). Provide via URI, media_asset, or base64 (max 100 MB).
             */
            depth_pano_image: components["schemas"]["MediaAssetReference"] | components["schemas"]["UriReference"] | components["schemas"]["DataBase64Reference"];
            /**
             * Seed
             * @description Random seed for reproducible generation.
             */
            seed?: number | null;
            /**
             * Text Prompt
             * @description Text description of the desired appearance.
             */
            text_prompt: string;
            /**
             * Z Max
             * @description Maximum depth. Required for PNG depth maps (normalized to [0, 1]). Must be provided together with z_min and must be greater than z_min. Omit for EXR depth maps.
             */
            z_max?: number | null;
            /**
             * Z Min
             * @description Minimum depth. Required for PNG depth maps (normalized to [0, 1]). Must be provided together with z_max. Omit for EXR depth maps.
             */
            z_min?: number | null;
        };
        /**
         * PanoDepthToRgbResult
         * @description Result from depth-to-RGB panorama generation.
         *
         *     Returned inside ``Operation.response`` when the
         *     operation completes successfully (``done=true``).
         */
        PanoDepthToRgbResult: {
            /**
             * Pano Url
             * @description URL of the generated RGB panorama image. Available when the operation succeeds.
             */
            pano_url?: string | null;
        };
        /**
         * Permission
         * @description Access control permissions for a resource.
         */
        Permission: {
            /**
             * Allow Id Access
             * @default false
             */
            allow_id_access: boolean;
            /** Allowed Readers */
            allowed_readers?: string[];
            /** Allowed Writers */
            allowed_writers?: string[];
            /**
             * Public
             * @default false
             */
            public: boolean;
        };
        /**
         * Prompt
         * @description For world models generating a world from a single image (+ text).
         *     Images can be generated using the :image-generation method.
         *     If no text prompt is provided, it will be generated via recaption.
         */
        Prompt: {
            image_prompt: components["schemas"]["Content"];
            /**
             * Is Pano
             * @default false
             */
            is_pano: boolean;
            /** Text Prompt */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
        };
        /**
         * SphericallyLocatedContent
         * @description Content with a preferred location on the sphere.
         */
        "SphericallyLocatedContent-Input": {
            /**
             * Azimuth
             * @description Azimuth angle in degrees
             */
            azimuth?: number | null;
            /**
             * Content
             * @description The content at this location
             */
            content: components["schemas"]["MediaAssetReference"] | components["schemas"]["UriReference"] | components["schemas"]["DataBase64Reference"];
        };
        /**
         * SphericallyLocatedContent
         * @description Content with a preferred location on the sphere.
         */
        "SphericallyLocatedContent-Output": {
            /** Azimuth */
            azimuth?: number | null;
            /** Data Base64 */
            data_base64?: string | null;
            /**
             * Extension
             * @description File extension without dot
             * @example jpg
             * @example png
             * @example pdf
             * @example txt
             */
            extension?: string | null;
            /** Uri */
            uri?: string | null;
        };
        /**
         * SplatAssets
         * @description Gaussian splat asset URLs.
         */
        SplatAssets: {
            /** @description Semantic metadata for the world */
            semantics_metadata?: components["schemas"]["WorldSemanticsMetadata"] | null;
            /**
             * Spz Urls
             * @description URLs for SPZ format Gaussian splat files
             */
            spz_urls?: {
                [key: string]: string;
            } | null;
        };
        /**
         * UploadUrlInfo
         * @description Information required to upload raw bytes directly to storage.
         */
        UploadUrlInfo: {
            /**
             * Curl Example
             * @description Optional curl example for convenience
             */
            curl_example?: string | null;
            /**
             * Required Headers
             * @description Headers that MUST be included when uploading (e.g. Content-Type)
             */
            required_headers?: {
                [key: string]: string;
            } | null;
            /**
             * Upload Method
             * @description Upload method
             */
            upload_method: string;
            /**
             * Upload Url
             * @description Signed URL for uploading bytes via PUT
             */
            upload_url: string;
        };
        /**
         * UriReference
         * @description Reference to content via a publicly accessible URL.
         */
        UriReference: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "uri";
            /**
             * Uri
             * @description Publicly accessible URL pointing to the media
             */
            uri: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VideoPrompt
         * @description Video-to-world generation.
         *
         *     Generates a world from a video. text_prompt is optional.
         *
         *     Recommended video formats: mp4, webm, mov, avi.
         *     Maximum video size: 100MB.
         */
        "VideoPrompt-Input": {
            /**
             * Disable Recaption
             * @description If True, use text_prompt as-is without recaptioning
             */
            disable_recaption?: boolean | null;
            /**
             * Text Prompt
             * @description Optional text guidance (auto-generated if not provided)
             */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
            /**
             * Video Prompt
             * @description Video content for world generation
             */
            video_prompt: components["schemas"]["MediaAssetReference"] | components["schemas"]["UriReference"] | components["schemas"]["DataBase64Reference"];
        };
        /**
         * VideoPrompt
         * @description For world models supporting video (+ text) input.
         */
        "VideoPrompt-Output": {
            /** Text Prompt */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
            video_prompt: components["schemas"]["Content"];
        };
        /**
         * World
         * @description A generated world, including asset URLs.
         */
        World: {
            /** @description Generated world assets */
            assets?: components["schemas"]["WorldAssets"] | null;
            /**
             * Created At
             * @description Creation timestamp
             */
            created_at?: string | null;
            /**
             * Display Name
             * @description Display name
             */
            display_name: string;
            /**
             * Model
             * @description Model used for generation
             */
            model?: string | null;
            /** @description Access control permissions for the world */
            permission?: components["schemas"]["Permission"] | null;
            /**
             * Tags
             * @description Tags associated with the world
             */
            tags?: string[] | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
            /**
             * World Id
             * @description World identifier
             */
            world_id: string;
            /**
             * World Marble Url
             * @description World Marble URL
             */
            world_marble_url: string;
            /**
             * World Prompt
             * @description World prompt
             */
            world_prompt?: (components["schemas"]["WorldTextPrompt-Output"] | components["schemas"]["Prompt"] | components["schemas"]["MultiImagePrompt-Output"] | components["schemas"]["VideoPrompt-Output"] | components["schemas"]["DepthPanoPrompt"] | components["schemas"]["InpaintPanoPrompt"]) | null;
        };
        /**
         * WorldAssets
         * @description Downloadable outputs of world generation.
         */
        WorldAssets: {
            /**
             * Caption
             * @description AI-generated description of the world
             */
            caption?: string | null;
            /** @description Imagery assets */
            imagery?: components["schemas"]["ImageryAssets"] | null;
            /** @description Mesh assets */
            mesh?: components["schemas"]["MeshAssets"] | null;
            /** @description Gaussian splat assets */
            splats?: components["schemas"]["SplatAssets"] | null;
            /**
             * Thumbnail Url
             * @description Thumbnail URL for the world
             */
            thumbnail_url?: string | null;
        };
        /**
         * WorldSemanticsMetadata
         * @description Semantic metadata for world generation output.
         */
        WorldSemanticsMetadata: {
            /** Ground Plane Offset */
            ground_plane_offset?: number | null;
            /** Metric Scale Factor */
            metric_scale_factor?: number | null;
        };
        /**
         * WorldTextPrompt
         * @description Text-to-world generation.
         *
         *     Generates a world from a text description. text_prompt is REQUIRED.
         */
        "WorldTextPrompt-Input": {
            /**
             * Disable Recaption
             * @description If True, use text_prompt as-is without recaptioning
             */
            disable_recaption?: boolean | null;
            /**
             * Text Prompt
             * @description Optional text guidance (auto-generated if not provided)
             */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /**
         * WorldTextPrompt
         * @description Input prompt class for text-conditioned world generation.
         */
        "WorldTextPrompt-Output": {
            /** Text Prompt */
            text_prompt?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /**
         * WorldsGenerateRequest
         * @description Request to generate a world from text, image, multi-image, or video input.
         * @example {
         *       "display_name": "Enchanted Forest",
         *       "model": "marble-1.0",
         *       "permission": {
         *         "public": false
         *       },
         *       "seed": 42,
         *       "tags": [
         *         "fantasy",
         *         "nature"
         *       ],
         *       "world_prompt": {
         *         "text_prompt": "A mystical forest with glowing mushrooms",
         *         "type": "text"
         *       }
         *     }
         * @example {
         *       "display_name": "World from Image",
         *       "model": "marble-1.0-draft",
         *       "world_prompt": {
         *         "image_prompt": {
         *           "source": "uri",
         *           "uri": "https://example.com/my-image.jpg"
         *         },
         *         "is_pano": false,
         *         "text_prompt": "A beautiful landscape",
         *         "type": "image"
         *       }
         *     }
         * @example {
         *       "permission": {
         *         "public": true
         *       },
         *       "world_prompt": {
         *         "type": "video",
         *         "video_prompt": {
         *           "media_asset_id": "550e8400e29b41d4a716446655440000",
         *           "source": "media_asset"
         *         }
         *       }
         *     }
         * @example {
         *       "display_name": "World from Multiple Images",
         *       "model": "marble-1.1",
         *       "world_prompt": {
         *         "multi_image_prompt": [
         *           {
         *             "azimuth": 0,
         *             "content": {
         *               "source": "uri",
         *               "uri": "https://example.com/image1.jpg"
         *             }
         *           },
         *           {
         *             "azimuth": 180,
         *             "content": {
         *               "source": "uri",
         *               "uri": "https://example.com/image2.jpg"
         *             }
         *           }
         *         ],
         *         "type": "multi-image"
         *       }
         *     }
         */
        WorldsGenerateRequest: {
            /**
             * Display Name
             * @description Optional display name (max 64 characters)
             */
            display_name?: string | null;
            /**
             * Model
             * @description The model to use for generation. marble-1.1-plus includes dynamic world sizing. Legacy names ('Marble 0.1-plus', etc.) still work but are deprecated and will be removed in a future release.
             * @default marble-1.0
             */
            model: ("marble-1.0-draft" | "marble-1.0" | "marble-1.1" | "marble-1.1-plus") | ("Marble 0.1-mini" | "Marble 0.1-plus" | "Marble 1.1-plus");
            /**
             * @description The permission for the world
             * @default {
             *       "allow_id_access": false,
             *       "allowed_readers": [],
             *       "allowed_writers": [],
             *       "public": false
             *     }
             */
            permission: components["schemas"]["Permission"];
            /**
             * Seed
             * @description Random seed for generation
             */
            seed?: number | null;
            /**
             * Tags
             * @description Optional tags for the world (max 10 tags, each up to 32 characters)
             */
            tags?: string[] | null;
            /**
             * World Prompt
             * @description The prompt specifying how to generate the world
             */
            world_prompt: components["schemas"]["WorldTextPrompt-Input"] | components["schemas"]["ImagePrompt"] | components["schemas"]["MultiImagePrompt-Input"] | components["schemas"]["VideoPrompt-Input"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_media_asset_marble_v1_media_assets__media_asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAsset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_media_asset_upload_marble_v1_media_assets_prepare_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaAssetPrepareUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetPrepareUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_marble_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOperationResponse_Union_World__PanoDepthToRgbResult__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pano_depth_to_rgb_marble_v1_pano_depth_to_rgb_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PanoDepthToRgbRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation_PanoDepthToRgbResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_world_marble_v1_worlds__world_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["World"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_world_marble_v1_worlds__world_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteWorldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_world_marble_v1_worlds_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorldsGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWorldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_worlds_marble_v1_worlds_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListWorldsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWorldsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
